[features]
seeds = false
skip-lint = false
[programs.localnet]
bonkinator = "AM11xAodtV57L3Zuo2y23WERsyASJtXTzpYh2oarqsh5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/zazza/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
